// Command seedskills is TG-36's seeding rail: the idempotent wire from the reviewed distillate
// tree (skills/, 48 artifacts — 12 skill + 36 runbook, generated by tools/prosedistill from the
// 79-entry manifest truth) into skill-store DRAFT rows, through the store's EXISTING governed
// write path and nothing else.
//
// # What a run does
//
//   - loads tools/prosedistill/manifest.json and the skills/ tree, and cross-validates them:
//     strays, missing files, frontmatter↔manifest disagreement, classes outside {skill,
//     runbook}, bodies outside the store's own per-class caps, predicates outside the store's
//     closed vocabulary — ANY of these refuses the whole run (drift is reconciled by a human,
//     never written around);
//   - plans each artifact against the store: an identical-ContentHash version of the same name
//     anywhere in its history → skip-identical (so a re-run is a no-op); a pinned identity, a
//     class flip, a same-version-different-hash collision, or a name owned by a non-distill
//     writer → refuse; otherwise → create;
//   - on --execute: PutSkill (identity upsert — preserves operator descriptions by the store's
//     own CASE rule) + CreateVersion (draft; rationale = the fixed provenance sentence citing
//     the source and TG-477/TG-478/TG-479/TG-85/TG-78; Source = distill:<path>; Author tool:seedskills).
//
// # The TG-489 chain
//
// Chain participation is INTERNAL to the store's writers (core/db/skillstore.go CreateVersion:
// head locked FOR UPDATE, row linked, head advanced — one transaction; an uninitialized chain
// fails the append closed). This tool therefore writes through CreateVersion untouched and
// handles the chain exactly as worker boot does: EnsureChain BEFORE seeding (initializes a
// fresh store; never heals — a mismatched link aborts loudly), and VerifyChainRead AFTER, so a
// seeding run ends with the corpus proving itself or the run exiting nonzero.
//
// # applies_when — the seeding policy
//
// Frontmatter carries no applies_when, so every artifact seeds with the EMPTY predicate: an
// unscoped draft. Drafts never compose (only production rows reach the agent seed), so an
// unscoped draft is inert; scoping happens where the eval evidence lives — per-artifact
// admission/trial, or an operator — not at this wire. A manifest entry MAY carry a `predicate`
// field ({"phases":[...],"exec_classes":[...],"domains":[...]}); it is validated against the
// store's closed vocabulary and rides the draft. Today no entry does.
//
// # Gates and arming
//
// Per the owner rulings on TG-488 and the 2026-08-14 gate ruling, this wire is NOT
// merge-eval-gated: the binding evals attach per-artifact at admission/trial, after seeding.
// Seeding any real store is a COORDINATOR act (TG-36) — this tool ships disarmed: the default
// is a dry-run that writes nothing, and the real write requires BOTH --execute and TG_SEED_DSN.
//
// Usage:
//
//	go run ./tools/seedskills                          # DRY-RUN (default): validate + plan, write nothing
//	TG_SEED_DSN=... go run ./tools/seedskills          # dry-run with store-aware plan (reads only)
//	TG_SEED_DSN=... go run ./tools/seedskills --execute  # seed draft rows, then verify the chain
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/territory-grounder/grounder/core/db"
	"github.com/territory-grounder/grounder/core/skillstore"
)

// dbStore adapts the pgx-backed skill store to the seeder's Store surface using only EXISTING
// store API: SkillDetail (the console's history read) for state, PutSkill/CreateVersion for the
// writes.
type dbStore struct{ s *db.SkillStore }

func (d dbStore) State(ctx context.Context, name string) (StoreState, error) {
	det, found, err := d.s.SkillDetail(ctx, name)
	if err != nil {
		return StoreState{}, err
	}
	if !found {
		return StoreState{}, nil
	}
	st := StoreState{
		Found: true,
		Identity: skillstore.Skill{
			Name:        det.Name,
			Kind:        det.Kind,
			Pinned:      det.Pinned,
			Class:       skillstore.ArtifactClass(det.ArtifactClass),
			Position:    det.Position,
			Description: det.Description,
		},
	}
	for _, v := range det.Versions {
		st.Versions = append(st.Versions, StoredVersion{Version: v.Version, ContentHash: v.ContentHash, Source: v.Source})
	}
	return st, nil
}

func (d dbStore) PutSkill(ctx context.Context, sk skillstore.Skill) error {
	return d.s.PutSkill(ctx, sk)
}

func (d dbStore) CreateVersion(ctx context.Context, v skillstore.Version) (skillstore.Version, error) {
	return d.s.CreateVersion(ctx, v)
}

// findRepoRoot walks upward to the module root, so the tool runs from any subdirectory (the
// same convention as prosedistill).
func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("no go.mod above the working directory — run from inside the repo")
		}
		dir = parent
	}
}

func printPlan(p Plan) {
	for _, it := range p.Items {
		fmt.Printf("  %-14s %-8s %-28s v%s  %s\n", it.Action, it.Artifact.Class, it.Artifact.Name, it.Artifact.Version, it.Reason)
	}
}

func run() error {
	execute := flag.Bool("execute", false,
		"actually write draft rows (requires TG_SEED_DSN). Without it this is a DRY-RUN: plan only, nothing written")
	flag.Parse()
	ctx := context.Background()

	root, err := findRepoRoot()
	if err != nil {
		return err
	}
	arts, err := loadCorpus(root)
	if err != nil {
		return err
	}
	perClass := map[skillstore.ArtifactClass]int{}
	for _, a := range arts {
		perClass[a.Class]++
	}
	fmt.Printf("seedskills: corpus OK — %d artifacts (%d skill + %d runbook) agree with the manifest\n",
		len(arts), perClass[skillstore.ClassSkill], perClass[skillstore.ClassRunbook])

	dsn := os.Getenv("TG_SEED_DSN")
	if *execute && dsn == "" {
		return errors.New("--execute requires TG_SEED_DSN — seeding a real store is a coordinator act (TG-36); this tool never guesses a database")
	}

	var st Store
	var skillDB *db.SkillStore
	if dsn != "" {
		pool, cerr := db.Connect(ctx, dsn)
		if cerr != nil {
			return fmt.Errorf("connect TG_SEED_DSN: %w", cerr)
		}
		defer pool.Close()
		skillDB = db.NewSkillStore(pool)
		if *execute {
			// The worker-boot mirror: initialize a fresh chain, verify an existing one. EnsureChain
			// NEVER heals — a mismatched link aborts here, before any write.
			rep, cerr := skillDB.EnsureChain(ctx)
			if cerr != nil {
				return fmt.Errorf("distillate chain: %w", cerr)
			}
			if !rep.OK {
				return fmt.Errorf("distillate chain refuses seeding: %s", rep)
			}
			fmt.Printf("seedskills: pre-seed %s\n", rep)
		} else {
			// Dry-run writes NOTHING — including chain initialization — so this is the read-only
			// verify. An uninitialized chain is a fresh store; --execute (or worker boot) initializes.
			rep, cerr := skillDB.VerifyChainRead(ctx)
			if cerr != nil {
				return fmt.Errorf("distillate chain: %w", cerr)
			}
			fmt.Printf("seedskills: %s\n", rep)
			if !rep.OK && rep.Reason != skillstore.ChainReasonUninitialized {
				fmt.Println("seedskills: NOTE — --execute will REFUSE against this store until the chain is reconciled")
			}
		}
		st = dbStore{skillDB}
	}

	p, err := buildPlan(ctx, arts, st)
	if err != nil {
		return err
	}
	printPlan(p)
	pc := p.counts()

	if !*execute {
		mode := "offline (no TG_SEED_DSN — idempotency/occupancy decided at --execute)"
		if p.StoreAware {
			mode = "store-aware"
		}
		fmt.Printf("seedskills DRY-RUN (%s): would create %d, skip %d identical, refuse %d — NOTHING WRITTEN\n",
			mode, pc.Created, pc.Skipped, pc.Refused)
		if pc.Refused > 0 {
			return fmt.Errorf("dry-run found %d refusals — reconcile before --execute", pc.Refused)
		}
		return nil
	}

	c, err := apply(ctx, p, st)
	if err != nil {
		return err
	}
	rep, err := skillDB.VerifyChainRead(ctx)
	if err != nil {
		return fmt.Errorf("post-seed chain verify: %w", err)
	}
	if !rep.OK {
		return fmt.Errorf("post-seed chain verify FAILED: %s", rep)
	}
	fmt.Printf("seedskills: created %d, skipped %d identical, refused %d\n", c.Created, c.Skipped, c.Refused)
	fmt.Printf("seedskills: post-seed %s\n", rep)
	return nil
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "seedskills:", err)
		os.Exit(1)
	}
}
