package preflight

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/pem"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/crypto/ssh"

	"github.com/territory-grounder/grounder/core/config"
)

// writeValidKey generates a real ed25519 SSH private key at RUNTIME and writes it to a temp file, returning
// the path. The PEM marker exists only in the generated bytes at runtime — never as a literal in source —
// so scripts/lint-forbidden.sh 4/4 (no contiguous PEM marker in source) stays green without a fixture.
func writeValidKey(t *testing.T) string {
	t.Helper()
	_, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generate ed25519 key: %v", err)
	}
	block, err := ssh.MarshalPrivateKey(priv, "")
	if err != nil {
		t.Fatalf("marshal private key: %v", err)
	}
	pemBytes := pem.EncodeToMemory(block)
	// Sanity: the bytes we just built must actually parse (guards the fixture itself).
	if _, err := ssh.ParsePrivateKey(pemBytes); err != nil {
		t.Fatalf("generated key does not parse: %v", err)
	}
	path := filepath.Join(t.TempDir(), "one_key")
	if err := os.WriteFile(path, pemBytes, 0o600); err != nil {
		t.Fatalf("write key: %v", err)
	}
	return path
}

func writeFile(t *testing.T, name, contents string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
	return path
}

func TestCheckSSHKeys(t *testing.T) {
	validPath := writeValidKey(t)
	emptyPath := writeFile(t, "empty_key", "")
	garbagePath := writeFile(t, "garbage_key", "this is not a private key\n")
	missingPath := filepath.Join(t.TempDir(), "does-not-exist")

	tests := []struct {
		name       string
		refs       []SSHKeyRef
		wantFailed bool
		wantConfig int
		wantReason string // substring expected in the (first) failure reason, when wantFailed
	}{
		{
			name:       "valid key present and readable passes",
			refs:       []SSHKeyRef{{Name: "actuation", Ref: config.SecretRef("file:" + validPath)}},
			wantFailed: false,
			wantConfig: 1,
		},
		{
			name:       "missing key file fails loud",
			refs:       []SSHKeyRef{{Name: "actuation", Ref: config.SecretRef("file:" + missingPath)}},
			wantFailed: true,
			wantConfig: 1,
			wantReason: "did not resolve",
		},
		{
			name:       "present but empty fails",
			refs:       []SSHKeyRef{{Name: "actuation", Ref: config.SecretRef("file:" + emptyPath)}},
			wantFailed: true,
			wantConfig: 1,
			wantReason: "resolved empty",
		},
		{
			name:       "present but unparseable fails",
			refs:       []SSHKeyRef{{Name: "actuation", Ref: config.SecretRef("file:" + garbagePath)}},
			wantFailed: true,
			wantConfig: 1,
			wantReason: "did not parse",
		},
		{
			name:       "unset env ref fails (env not set)",
			refs:       []SSHKeyRef{{Name: "actuation", Ref: config.SecretRef("env:TG_TEST_UNSET_KEY_REF_XYZ")}},
			wantFailed: true,
			wantConfig: 1,
			wantReason: "did not resolve",
		},
		{
			name:       "empty ref is skipped (not configured)",
			refs:       []SSHKeyRef{{Name: "actuation", Ref: config.SecretRef("")}},
			wantFailed: false,
			wantConfig: 0,
		},
		{
			name: "mixed: one good one missing fails overall",
			refs: []SSHKeyRef{
				{Name: "actuation", Ref: config.SecretRef("file:" + validPath)},
				{Name: "hostdiag", Ref: config.SecretRef("file:" + missingPath)},
			},
			wantFailed: true,
			wantConfig: 2,
			wantReason: "did not resolve",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			rep := CheckSSHKeys(tc.refs)
			if rep.Failed() != tc.wantFailed {
				t.Fatalf("Failed()=%v want %v (summary: %s)", rep.Failed(), tc.wantFailed, rep.Summary())
			}
			if rep.Ready() == tc.wantFailed {
				t.Fatalf("Ready()=%v must be the negation of Failed()=%v", rep.Ready(), rep.Failed())
			}
			if rep.Configured() != tc.wantConfig {
				t.Fatalf("Configured()=%d want %d", rep.Configured(), tc.wantConfig)
			}
			if tc.wantFailed {
				if len(rep.Failures) == 0 {
					t.Fatalf("expected at least one failure")
				}
				if tc.wantReason != "" {
					found := false
					for _, f := range rep.Failures {
						if strings.Contains(f.Reason, tc.wantReason) {
							found = true
						}
						// Redaction: a failure reason must never echo key material.
						if strings.Contains(f.Reason, "PRIVATE KEY") {
							t.Fatalf("failure reason leaked key material: %q", f.Reason)
						}
					}
					if !found {
						t.Fatalf("no failure reason contained %q; got %s", tc.wantReason, rep.Summary())
					}
				}
			}
		})
	}
}

// TestUnreadableKeyPermsFailsAsNonRoot proves the exact incident failure mode: a key file the runtime user
// cannot READ (mode 0000) fails the preflight. Root bypasses file permissions, so when the test runs as
// root (the CI golang image) we document the bypass instead of asserting a false result — the preflight's
// value there is that it runs IN the worker process (uid 65532), which this simulates by uid identity.
func TestUnreadableKeyPermsFailsAsNonRoot(t *testing.T) {
	path := writeValidKey(t)
	if err := os.Chmod(path, 0o000); err != nil {
		t.Fatalf("chmod 0000: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(path, 0o600) })

	rep := CheckSSHKeys([]SSHKeyRef{{Name: "actuation", Ref: config.SecretRef("file:" + path)}})
	if os.Geteuid() == 0 {
		t.Logf("running as root — file permissions are bypassed; the preflight relies on running IN the "+
			"worker process (uid:gid 65532), where an unreadable key fails. Report: %s", rep.Summary())
		return
	}
	if !rep.Failed() {
		t.Fatalf("a mode-0000 key must fail the preflight for a non-root user; got ready. Summary: %s", rep.Summary())
	}
	if !strings.Contains(rep.Summary(), "did not resolve") {
		t.Fatalf("unreadable key should fail at resolve; got %s", rep.Summary())
	}
}

func TestSSHKeyRefsFromEnv(t *testing.T) {
	env := map[string]string{
		"TG_ACTUATION_SSH_KEY":       "file:/secrets/one_key",
		"TG_SYSLOGNG_DEPLOYMENTS":    "NL|dc1syslogng01|root|file:/secrets/syslog_key|/mnt/logs ; GR|dc2syslogng01|svc|env:GR_SYSLOG_KEY|",
		"TG_HOSTDIAG_DEPLOYMENTS":    "nl|dc1*|root|file:/secrets/hostdiag_key ; gr|dc2*|svc|file:/secrets/one_key",
		"TG_CREDENTIAL_NATIVE_RULES": "host:stranger01|nativeuser|22|ssh|file:/secrets/native_key ; group:api|svc|443|api|env:SOME_API_TOKEN|env:SOME_API_TOKEN ; dev:jun|admin|830|netconf|file:/secrets/netconf_key",
	}
	get := func(k string) string { return env[k] }

	refs := SSHKeyRefsFromEnv(get)
	got := map[string]bool{}
	for _, r := range refs {
		got[string(r.Ref)] = true
	}

	// Every SSH-key ref must be collected, deduplicated by value (one_key appears in actuation + hostdiag).
	wantPresent := []string{
		"file:/secrets/one_key",
		"file:/secrets/syslog_key",
		"env:GR_SYSLOG_KEY",
		"file:/secrets/hostdiag_key",
		"file:/secrets/native_key",
		"file:/secrets/netconf_key",
	}
	for _, w := range wantPresent {
		if !got[w] {
			t.Errorf("expected SSH key ref %q to be collected; got %v", w, keys(got))
		}
	}
	// The api-scheme rule's token field must NOT be collected as an SSH key.
	if got["env:SOME_API_TOKEN"] {
		t.Errorf("api-token ref must not be parsed as an SSH private key; got %v", keys(got))
	}
	// Dedup: one_key collected exactly once despite two references.
	oneKeyCount := 0
	for _, r := range refs {
		if string(r.Ref) == "file:/secrets/one_key" {
			oneKeyCount++
		}
	}
	if oneKeyCount != 1 {
		t.Errorf("file:/secrets/one_key should be deduplicated to one ref; got %d", oneKeyCount)
	}

	// Empty environment collects nothing.
	if n := len(SSHKeyRefsFromEnv(func(string) string { return "" })); n != 0 {
		t.Errorf("empty env should yield no SSH key refs; got %d", n)
	}
}

func keys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
