package main

// END-TO-END: THE GENERATED ALLOWLIST AGAINST THE REAL GUARD SCRIPT (TG-280).
//
// The unit tests above prove the generator emits the catalogue faithfully. That is not the property that
// protects the estate. The property that protects the estate is that the shell script installed on 38
// hosts, reading the file this tool writes, ADMITS every command TG sends and REFUSES everything else.
//
// Those are different claims, and this repo has a documented history of proving the first and shipping
// the second broken. So this test runs the actual `deploy/readonly-guard/tg-readonly-guard` against the
// actual generated file, with `sh`, exactly as sshd would.

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/territory-grounder/grounder/modules/observability/hostdiag"
)

const guardScript = "../../deploy/readonly-guard/tg-readonly-guard"

// runGuard invokes the guard the way sshd does: SSH_ORIGINAL_COMMAND in the env, no arguments. It
// replaces the exec'd command with `true` via PATH so an ALLOW does not actually run `df` on the test
// machine — what is under test is the DECISION, not the command.
func runGuard(t *testing.T, allowFile, cmd string) int {
	t.Helper()
	stub := t.TempDir()
	for _, bin := range []string{"df", "uptime", "systemctl", "docker", "ps", "free", "du", "findmnt",
		"journalctl", "tail", "grep", "logger", "eval"} {
		// `grep` must stay REAL — the guard uses it to match. Everything the guard might exec is stubbed.
		if bin == "grep" || bin == "logger" {
			continue
		}
		if err := os.WriteFile(filepath.Join(stub, bin), []byte("#!/bin/sh\nexit 0\n"), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	c := exec.Command("sh", guardScript)
	c.Env = append(os.Environ(),
		"SSH_ORIGINAL_COMMAND="+cmd,
		"TG_READONLY_ALLOWFILE="+allowFile,
		"PATH="+stub+string(os.PathListSeparator)+os.Getenv("PATH"))
	if err := c.Run(); err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return ee.ExitCode()
		}
		t.Fatalf("run guard: %v", err)
	}
	return 0
}

func writeAllow(t *testing.T) string {
	t.Helper()
	lines, err := render(hostdiag.ReadOnlyWireCommands(), hostdiag.ReadOnlyCheckCount(),
		[]string{"/var/log/syslog"}, 500)
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	p := filepath.Join(t.TempDir(), "tg-readonly-guard.allow")
	if err := os.WriteFile(p, []byte(strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

// KILLING MUTATION: change one byte of any catalogue argv, or of the guard's grep flags (-qxF -> -q).
// RED. This is the assertion that says "the agent can still see the estate".
func TestTheGuardAdmitsEveryCommandTgActuallySends(t *testing.T) {
	allow := writeAllow(t)
	cmds := hostdiag.ReadOnlyWireCommands()
	if len(cmds) == 0 {
		t.Fatal("no commands to test — this would pass by checking nothing")
	}
	for _, c := range cmds {
		if rc := runGuard(t, allow, c); rc != 0 {
			t.Errorf("the guard REFUSED a command TG sends (rc=%d): %s\n"+
				"Installed on the estate this denies a real diagnostic, and the lane reports a denied "+
				"read as an unreachable host — so the agent goes blind and the estate looks quiet.", rc, c)
		}
	}
}

// The other half. A guard that admits everything is not a guard, and 42 specifically (not 1) is what
// lets the caller distinguish a refusal from an unreachable host.
func TestTheGuardRefusesEverythingElseWithExit42(t *testing.T) {
	allow := writeAllow(t)
	hostile := map[string]string{
		"arbitrary root command":   `'rm' '-rf' '/'`,
		"command injection":        `'uptime'; id`,
		"shell":                    `'/bin/sh'`,
		"a mutation in TG grammar": `'systemctl' 'restart' 'nginx.service'`,
		"an unlisted log file":     `'tail' '-n' '50' '--' '/etc/shadow'`,
		"an oversized tail":        `'tail' '-n' '999999' '--' '/var/log/syslog'`,
		"a comment line":           `# GENERATED by tools/readallow from the hostdiag catalogue — do not hand-edit.`,
		"interactive session":      ``,
		"a near miss":              `'df' '-h' `,
	}
	for name, cmd := range hostile {
		if rc := runGuard(t, allow, cmd); rc != 42 {
			t.Errorf("%s was NOT refused with exit 42 (got rc=%d): %q\n"+
				"A leaked diagnostic key would be able to do this as root on every host TG reads.",
				name, rc, cmd)
		}
	}
}

// FAIL CLOSED. A missing allowlist is the realistic deployment failure — the guard rolled out, the file
// did not. It must deny, never default to permissive.
func TestAMissingAllowlistDeniesRatherThanDefaultsOpen(t *testing.T) {
	missing := filepath.Join(t.TempDir(), "not-deployed.allow")
	if rc := runGuard(t, missing, `'uptime'`); rc != 42 {
		t.Fatalf("rc=%d with no allowlist present, want 42 — a half-finished rollout would leave the "+
			"key unconstrained on exactly the hosts where the file failed to land", rc)
	}
}
