// Command readallow renders the READ-ONLY host guard's allowlist FROM THE DIAGNOSTIC CATALOGUE (TG-280).
//
// WHAT IT IS FOR. TG's host-diagnostics lane reads every estate host as root with /secrets/one_key — the
// unrestricted estate root key, mounted readable into a worker that also processes untrusted alert and
// syslog content. TG's own gates cannot constrain that key: they bind the commands TG constructs, and a
// leaked key is driven by a stock SSH client. The only control that binds the KEY is the server's own
// sshd, via `restrict,command="/usr/local/sbin/tg-readonly-guard"` on the authorized_keys entry.
//
// The guard compares SSH_ORIGINAL_COMMAND byte-for-byte against this list. So the list must be exactly
// what the client sends — which is why it is GENERATED from the same catalogue and the same quoting
// function the client uses, never hand-copied. tools/guardallow exists because the actuation allowlist
// was hand-authored and drifted; the identical mistake here would be worse, because a denied read
// returns a sentinel string that reads like a normal answer. A drifted read allowlist does not break
// loudly — it makes the agent silently blind, which is TG-271 all over again.
//
// Usage:
//
//	readallow                       # the fixed diagnostic catalogue
//	readallow -log-paths "/var/log/syslog /var/log/auth.log"   # also the syslog read shapes
//
// THE HOST REMAINS FINAL AUTHORITY. This only RENDERS a candidate list; an operator installs it.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/territory-grounder/grounder/modules/observability/hostdiag"
	"github.com/territory-grounder/grounder/modules/observability/syslogng"
)

func main() {
	logPaths := flag.String("log-paths", "", "space-separated log files the syslog reader may tail/grep")
	maxLines := flag.Int("max-lines", 500, "largest -n the tail shape may request")
	flag.Parse()

	lines, err := render(hostdiag.ReadOnlyWireCommands(), hostdiag.ReadOnlyCheckCount(),
		strings.Fields(*logPaths), *maxLines)
	if err != nil {
		fmt.Fprintln(os.Stderr, "readallow:", err)
		os.Exit(1)
	}
	for _, l := range lines {
		fmt.Println(l)
	}
}

// render builds the allowlist and refuses to emit a useless one.
//
// THE VACUITY FLOOR is the point of this function existing separately. An allowlist rendered from an
// empty catalogue installs perfectly and denies every read, and because a denied read returns
// "(<host> was unreachable or the read errored)" the operator sees a working system with a quiet estate.
// Emitting nothing must be an ERROR at generation time, where somebody is looking.
func render(catalogue []string, checkCount int, logPaths []string, maxLines int) ([]string, error) {
	if checkCount == 0 || len(catalogue) == 0 {
		return nil, fmt.Errorf("the diagnostic catalogue rendered %d command(s) from %d check(s) — "+
			"an empty allowlist installs cleanly and then denies every read, and this lane reports a "+
			"denied read as an unreachable host, so the estate would look quiet instead of blind",
			len(catalogue), checkCount)
	}
	out := make([]string, 0, len(catalogue)+len(logPaths)*2)
	out = append(out, "# GENERATED by tools/readallow from the hostdiag catalogue — do not hand-edit.")
	out = append(out, "# Byte-for-byte SSH_ORIGINAL_COMMAND strings; the guard matches with grep -qxF.")
	out = append(out, catalogue...)

	// The syslog reader's argv carries operator-chosen values (how many lines, which pattern), so those
	// two shapes cannot be byte-matched. They are rendered per PATH at the fixed sizes the reader uses,
	// which keeps the guard on exact matching. A pattern-matching guard is a parser, and a parser on
	// untrusted input inside a security boundary is how this kind of control gets bypassed.
	for _, p := range logPaths {
		if strings.ContainsAny(p, " '\"\n") {
			return nil, fmt.Errorf("log path %q contains whitespace or quotes — refusing to render a "+
				"line whose meaning depends on how the remote shell splits it", p)
		}
		for _, n := range tailSizes(maxLines) {
			out = append(out, syslogng.RemoteCommand([]string{"tail", "-n", n, "--", p}))
		}
	}
	return out, nil
}

// tailSizes are the discrete -n values the allowlist admits. Discrete, not a range, because the guard
// matches exact strings — and a small fixed set is also a rate limit of sorts: a leaked key cannot ask
// for an arbitrarily large slice of a log.
func tailSizes(max int) []string {
	all := []string{"50", "100", "200", "500"}
	out := make([]string, 0, len(all))
	for _, s := range all {
		if atoiSafe(s) <= max {
			out = append(out, s)
		}
	}
	return out
}

func atoiSafe(s string) int {
	n := 0
	for _, r := range s {
		if r < '0' || r > '9' {
			return 1 << 30
		}
		n = n*10 + int(r-'0')
	}
	return n
}
